### ISSUE TITLE
index-based range

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-parser-js#10]
It would be very useful getting some pointer (range) information inside AST linking it back to the source code string. Something like `range:[from, to]` in esprima.

**Comment by michaelficarra** [comment]
Dupe of #2. See also https://github.com/shapesecurity/shift-spec/pull/7. Note that you'll only have start position info, not end.

**Comment by drom** [comment]
I think `range` was more useful, but I am OK with `SourceLocation`.
Does `shift-parser-js` supports it already? Do I have option to enable/disable it?

**Comment by michaelficarra** [comment]
Not yet. It appears @ikarienator has finished the necessary work, but has not opened a PR yet.
