### ISSUE TITLE
ES6: SuperCalls and SuperProperty

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#100]
# [12.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-left-hand-side-expressions) Left-Hand-Side Expressions
### Syntax

<pre>
<i>MemberExpression</i>[Yield] :
    <i>SuperProperty</i>[?Yield]

<i>SuperProperty</i>[Yield] :
    <b>super</b> <b>[</b> <i>Expression</i><sub>[In, ?Yield]</sub> <b>]</b>
    <b>super</b> <b>.</b> <i>IdentifierName</i>

<i>CallExpression</i>[Yield] :
    <i>SuperCall</i><sub>[?Yield]</sub>

<i>SuperCall</i>[Yield] :
    <b>super</b> <i>Arguments</i><sub>[?Yield]</sub>
</pre>

#### [12.2.5.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer-static-semantics-early-errors)

<pre>
PropertyDefinition : MethodDefinition
</pre>

It is a Syntax Error if HasDirectSuper of MethodDefinition is true.
#### [14.1.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions-static-semantics-early-errors)

<pre>
FunctionDeclaration : function BindingIdentifier ( FormalParameters ) { FunctionBody }
FunctionDeclaration : function ( FormalParameters ) { FunctionBody }
FunctionExpression : function BindingIdentifieropt ( FormalParameters ) { FunctionBody }
</pre>

- It is a Syntax Error if FormalParameters Contains SuperProperty is true.
- It is a Syntax Error if FunctionBody Contains SupeProperty is true.
- It is a Syntax Error if FormalParameters Contains SuperCall is true.
- It is a Syntax Error if FunctionBody Contains SuperCall is true.
#### [14.4.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions-static-semantics-early-errors)

<pre>
GeneratorMethod : * PropertyName ( StrictFormalParameters ) { GeneratorBody }
</pre>

It is a Syntax Error if HasDirectSuper of GeneratorMethod is true .

<pre>
GeneratorDeclaration : function * BindingIdentifier ( FormalParameters ) { GeneratorBody }
</pre>

It is a Syntax Error if HasDirectSuper of GeneratorDeclaration is true .

<pre>
GeneratorExpression : function * BindingIdentifieropt ( FormalParameters ) { GeneratorBody }
</pre>

It is a Syntax Error if HasDirectSuper of GeneratorExpression is true .
#### [14.5.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions-static-semantics-early-errors)

<pre>
ClassTail : ClassHeritageopt { ClassBody }
</pre>

It is a Syntax Error if ClassHeritage is not prsented and the following algorithm evaluates to true:
- Let constructor be ConstructorMethod of ClassBody.
- If constructor is empty, return false.
- Return HasDirectSuper of constructor.

<pre>
ClassElement : MethodDefinition
</pre>

It is a Syntax Error if PropName of MethodDefinition is not "constructor" and HasDirectSuper of MethodDefinition is true.

<pre>
ClassElement : static MethodDefinition
</pre>

It is a Syntax Error if HasDirectSuper of MethodDefinition is true.

**Comment by michaelficarra** [comment]
Fixed by #102.
