### ISSUE TITLE
export default doesn't support names in function declarations and classes

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#122]
https://github.com/shapesecurity/shift-parser-js/blob/c09ff7de1bf96c17475d692ebf15a596d4500363/test/modules/export.js#L195-L198

**Comment by ikarienator** [comment]
Are they allowed?

**Comment by ikarienator** [comment]
I see...

**Comment by michaelficarra** [comment]
They are optional.

**Comment by michaelficarra** [comment]
This was fixed by https://github.com/shapesecurity/shift-parser-js/pull/124.
