### ISSUE TITLE
`isDestructuringTarget` and `transformDestructuringAssignment` does not treat destructuring patterns differently but they are very different.

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#134]
``` es6
[a[0]=0]=[]
```

is valid but

``` es6
([a[0]=0]) => 0
```

is not.

**Comment by ikarienator** [comment]
@michaelficarra Can you address this issue?

**Comment by michaelficarra** [comment]
Yep, tomorrow.

**Comment by ikarienator** [comment]
I'm working on it. We were really really wrong about it.

**Comment by michaelficarra** [comment]
What? You might want to merge https://github.com/shapesecurity/shift-spec/pull/60 first.

**Comment by ikarienator** [comment]
Assignment Patterns and Binding Patterns are quite different, but we are parsing, checking and converting them using the same methods.

**Comment by michaelficarra** [comment]
Yeah I get that, that's the whole point of this issue. We need to make two sets of test/transform functions. I'll do it tomorrow.

**Comment by ikarienator** [comment]
I've finished it, I'll send PR soon. I just think it should be an improvement to not to parse binding patterns as left hand side expressions in the first place.
