### ISSUE TITLE
separate lexer into its own project

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#138]
This will enforce modularity and allow the validator to make use of the lexer for some of the validations it must do (`TemplateElement.rawValue`, `Directive.rawValue`, `IdentifierName`, etc.).

**Comment by ikarienator** [comment]
Lexer won't work without parser.

**Comment by michaelficarra** [comment]
Tell that to the sweet.js project.

**Comment by ikarienator** [comment]
Maybe we can simply expose the lexer from the parser project. I don't see the benefit of separating it into independent project, but I can see the engineering cost very clearly.

**Comment by michaelficarra** [comment]
But we can't then define the early error validator as a separate project because the parser will rely on the validator, which relies on the parser. Are we doomed to put them all in the same module?

**Comment by ikarienator** [comment]
Good point. Let me think about how to test it.
