### ISSUE TITLE
Make test fixtures each separate file(s) (esprima style)

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#142]
Clear benefits:
1. we can assign a meaningful name to each test case without introducing much code.
2. we don't need to worry about formatting mocha files (much).
3. easier to rebase.
4. if spec should change, the change on fixture can be done automatically.

**Comment by michaelficarra** [comment]
I don't think we can come up with meaningful names for 1700+ tests. And the other reasons are all trivial. I don't think these very minor benefits outweigh how difficult it would become to browse existing test cases. :-1:

**Comment by ikarienator** [comment]
If you think they are trivial, you should come up with an idea to automate changes on spec. If you think it's hard to navigate, try to not to use vim.

**Comment by ikarienator** [comment]
Tried it and it is not pleasant :weary:. Closing it now.
