### ISSUE TITLE
yield in arrow function parameter within generator

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#183]
`yield` expressions in arrow function parameters aren't handled correctly.

Test case:

``` javascript
var parseScript = require("shift-parser").parseScript;

function formals(ast) {
  return ast.body.statements[0].body.statements[0].expression.params.items[0];
}

var scriptAST = parseScript(`
function* g() {
  ((a = yield) => {})
}
`);
console.log(JSON.stringify(formals(scriptAST)));

var scriptAST = parseScript(`
function* g() {
  ((a = yield /a/g) => {})
}
`);
console.log(JSON.stringify(formals(scriptAST)));
```

The first example currently returns:

``` javascript
{
  "type": "BindingWithDefault",
  "binding": {"type": "BindingIdentifier","name": "a"},
  "init": {"type": "YieldExpression","expression": null}
}
```

The "init" node should be:

``` javascript
{"type":"IdentifierExpression","name":"yield"}
```

And the second example should throw a syntax error:
The lexical token sequence of `yield /a/g` is [`yield`, `RegularExpressionLiteral`] and this sequence cannot be parsed with no tokens left over as an `Initializer` expression within `ArrowFormalParameters`.

**Comment by michaelficarra** [comment]
I believe the current behaviour is correct. See

```
BindingElement[Yield,GeneratorParameter] :
  SingleNameBinding[?Yield, ?GeneratorParameter]
  [+GeneratorParameter] BindingPattern[?Yield,GeneratorParameter] Initializer[In]opt
  [~GeneratorParameter] BindingPattern[?Yield] Initializer[In, ?Yield]opt
```

The Initializer will be a YieldExpression as long as it's not in a generator parameter. Though I'm not an expert on this, so I defer to @ikarienator who implemented this part.

**Comment by anba** [comment]
> I believe the current behaviour is correct.
> The Initializer will be a YieldExpression as long as it's not in a generator parameter.

I'm confused what you mean by this. YieldExpressions cannot appear in parameter default initializers. The `yield` in `((a = yield) => {})` needs to be treated as an IdentifierExpression and the "init" node should reflect this.

**Comment by michaelficarra** [comment]
@anba

"YieldExpressions cannot appear in parameter default initializers" appears to be false: the Yield flag is passed all the way through _ArrowFunction -> ArrowParameters -> ArrowFormalParameters -> StrictFormalParameters -> FormalParameters -> FormalParameter -> BindingElement -> SingleNameBinding -> Initializer -> AssignmentExpression_.

Note that this is only the case for arrow functions and generators: function expressions, function statements, and non-generator methods do not pass the Yield flag to _FormalParameters_.

Test262 seems to get this wrong as well, at least when it comes to generator methods. See https://github.com/tc39/test262/issues/426

**Comment by anba** [comment]
Things have changed a bit after the _GeneratorParameter_ grammar parameter was removed. Both test cases should now throw a `SyntaxError` per 14.2.1, first bullet point:

> It is a Syntax Error if ArrowParameters Contains YieldExpression is true.

**Comment by anba** [comment]
> Test262 seems to get this wrong as well, at least when it comes to generator methods. See tc39/test262#426

This case is also handled through early error checks, 14.4.1:

> GeneratorMethod : \* PropertyName ( StrictFormalParameters ) { GeneratorBody }
> <ul><li>It is a Syntax Error if StrictFormalParameters Contains YieldExpression is true.
