### ISSUE TITLE
yield as function expression name in generators

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#184]
This code erroneously throws an error when parsed.

``` javascript
var parseScript = require("shift-parser").parseScript;
var scriptAST = parseScript(`
function* g() {
  (function yield {});
}
`);
console.log(JSON.stringify(scriptAST));
```

`FunctionExpression` has no `[Yield]` production parameter, so `yield` is always allowed as a `BindingIdentifier` for function expressions (except in strict mode).

**Comment by michaelficarra** [comment]
Confirmed.

**Comment by ariya** [comment]
Hmm, this is still the case with version 3.0.1:

``` js
> require('shift-parser').parseScript('function *g() { (function yield {}) }')
Error: [1:27]: Unexpected token "yield"
> require('shift-parser').parseScript('function *g() { (function yield() {}) }')
Error: [1:27]: Unexpected token "yield"
```

**Comment by michaelficarra** [comment]
Huh, I put in an [explicit failure test for this](https://github.com/shapesecurity/shift-parser-js/pull/218/files#diff-95fda822392088f2bff567cf3758cfe6R185). I guess it should have been the other way around?

**Comment by ariya** [comment]
If I understand the spec correctly, function declaration with `yield` should still fail.

**Comment by michaelficarra** [comment]
I'll have to look at the spec again.
