### ISSUE TITLE
class heritage expression not treated as strict mode code

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#185]
All parts of `ClassDeclaration` and `ClassExpression` are strict mode code, that includes the `ClassHeritage` expression.

Test case:

``` javascript
var parseScript = require("shift-parser").parseScript;

var scriptAST = parseScript(`
class C extends (eval = 0, null) {}
`);
console.log(JSON.stringify(scriptAST));

var scriptAST = parseScript(`
class C extends (delete foo, null) {}
`);
console.log(JSON.stringify(scriptAST));
```

Expected: Both scripts are rejected.
Actual: No syntax errors reported.

**Comment by michaelficarra** [comment]
PR at https://github.com/shapesecurity/shift-parser-js/pull/186, but it's blocked by a babel issue.
