### ISSUE TITLE
If an infinity literal is in the position of property name, what should it be parsed into?

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#19]
Between `PropertyName(Number, "Infinity")` or `PropertyName(Identifier, "Infinity")`?

**Comment by ikarienator** [comment]
If you codegen `{2e308:0}` to `{Infinity:0}`, it will not parse into the same program if the kind of the former one is `number`. So you need special treatment in `CodeGen.reducePropertyName`.

**Comment by ikarienator** [comment]
`{2e308:0}` is not syntactically different from `{Infinity:0}`. It raises the problem of whether we should have the `kind` field in `PropertName`.

**Comment by michaelficarra** [comment]
Okay, I agree. PropertyName should just have a normalised value with no `kind`. Please open an issue in shift-spec and link it here.

**Comment by michaelficarra** [comment]
For now, I think the kind should be `number`.
