### ISSUE TITLE
super() expression in default parameter initializer rejected

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#190]
super() expressions in default parameter initializer are rejected, but there is no early error rule which prohibits super() in that position (or at least I haven't found a rule which covers this case).

``` javascript
var parseScript = require("shift-parser").parseScript;
var scriptAST = parseScript(`
class C extends null {
  constructor(a = super()) {}
}
`);
console.log(JSON.stringify(scriptAST));
```

Expected: Parses successfully
Actual: Throws error `"Unexpected super call"`.

**Comment by michaelficarra** [comment]
`super()` in this position is disallowed for non-constructor methods.
- [14.5.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions-static-semantics-early-errors):

> It is a Syntax Error if PropName of MethodDefinition is not "constructor" and HasDirectSuper of MethodDefinition is true.
- [14.3.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions-static-semantics-hasdirectsuper):

> If StrictFormalParameters Contains SuperCall is true, return true.

But your example with a constructor method should be valid. Confirmed.

**Comment by michaelficarra** [comment]
Actually, I can't reproduce your result of "Unexpected super call". Are you sure you're trying the latest version?

**Comment by anba** [comment]
I'm using 2.0.0 (latest version per npm), maybe this was fixed already in master?

Later: Yes, it works when using the current `es6` branch.
