### ISSUE TITLE
Non-identifiers rejected in ExportSpecifier

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#191]
15.2.3.1 Static Semantics: Early Errors does not apply for `export ExportClause FromClause ;`.

``` javascript
var parseModule = require("shift-parser").parseModule;

var scriptAST = parseModule(`
  export {default as K} from "";
`);
console.log(JSON.stringify(scriptAST));

var scriptAST = parseModule(`
  export {static as K} from "";
`);
console.log(JSON.stringify(scriptAST));
```

Expected: Parses successfully
Actual: Throws `"Unexpected token default"` resp. `"Use of future reserved word in strict mode"`

**Comment by anba** [comment]
The second example throws `"Exported binding "static" is not declared"` in current es6 branch. (Probably same as #192)

**Comment by michaelficarra** [comment]
Confirmed the former. The latter is a duplicate of #192.

**Comment by anba** [comment]
Yup, just realized the 2nd example is the same as #192.
