### ISSUE TITLE
Imports are not registered as lexical names

### ISSUE THREAD

**Issue by anba** [shapesecurity/shift-parser-js#193]
Import statements create lexical names, cf. 

15.2.1.1 Static Semantics: Early Errors

```
It is a Syntax Error if any element of the ExportedBindings of ModuleItemList does not also occur in
either the VarDeclaredNames of ModuleItemList, or the LexicallyDeclaredNames of ModuleItemList.
```

and 15.2.1.11 Static Semantics: LexicallyDeclaredNames

```
ModuleItem : ImportDeclaration
1. Return the BoundNames of ImportDeclaration.
```

Test case:

``` javascript
var parseModule = require("shift-parser").parseModule;

var scriptAST = parseModule(`
  import e from "";
  export {e};
`);
console.log(JSON.stringify(scriptAST));

var scriptAST = parseModule(`
  import {e} from "";
  export {e};
`);
console.log(JSON.stringify(scriptAST));
```

Expected: parses successully
Actual: throws error `"Export 'e' is not defined in module"`

**Comment by michaelficarra** [comment]
Could not reproduce. Please make sure you confirm these on the latest `es6` commit.

**Comment by anba** [comment]
> Please make sure you confirm these on the latest es6 commit.

Oh sorry for the noise. I was using the current version from npm and I thought it was recent enough for testing. I'll make sure to use `es6` for further tests.
