### ISSUE TITLE
Future: noctals are non-standard, but widely supported

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#21]
`09`, `08`, `018`, etc. are not valid octal integer literals, but treated as decimal integer literals by implementations. We may want to willfully diverge from the standard here and support them.

**Comment by ikarienator** [comment]
I think it's now safe to say that we need a compatible-mode for parser.

**Comment by michaelficarra** [comment]
This has been addressed for ES6 by #118. While it'd be nice to back-port that support to ES5, I'm not going to leave an open issue for it. Closing, but patches welcome.
