### ISSUE TITLE
JS Error on IIAFE(Immediately invoked arrow function expression)

### ISSUE THREAD

**Issue by mohsen1** [shapesecurity/shift-parser-js#236]
Since "you can't do that, it's ugly" is not an option for AST composers!

``` js
()=>{}()
```

or 

``` js
()=>()
```

**Comment by michaelficarra** [comment]
These are not programs.

**Comment by mohsen1** [comment]
I'm not 100% sure about validity of this since `function(){}()` is invalid. But I've seen many instances of `()=>{}()` around. It also works in Babel.

**Comment by michaelficarra** [comment]
They're not programs. See https://github.com/babel/babel/issues/2154 and https://github.com/babel/babel/issues/2118.

**Comment by mohsen1** [comment]
Does `async` makes any difference?

```
async ()=>{

}() 
```

Because I've seen many instances like that. [here](https://github.com/jaydson/es7-async#the-new-awesome-beast-async-functions) and [here (without `async`)](http://jsrocks.org/2014/10/arrow-functions-and-their-scope/). I've also included it in my [proposal](https://github.com/mohsen1/async-json#with-await)

The wrapping parentheses shouldn't make any differences, right?

``` js
()=>{}() 
// vs
(()=>{}())
```

**Comment by mohsen1** [comment]
Just saw the links in edits you made. (GitHub is extremely slow for me). 

It's a Babel bug. Makes sense.

**Comment by michaelficarra** [comment]
FWIW, the jsrocks.org article explicitly calls out this pitfall:

> Using parentheses inside, as suggested by jsLint will not work

The others were just wrong, though. I've sent them PRs.

**Comment by mohsen1** [comment]
How about these?

``` js
_=>1
```

and

``` js
_=>1()
```

are they valid?

shift parser can parse them.

**Comment by michaelficarra** [comment]
Yes, they are valid.
