### ISSUE TITLE
es6 import statements not working after babel conversion

### ISSUE THREAD

**Issue by brokenalarms** [shapesecurity/shift-parser-js#239]
Apologies if this is not the right place to put this (maybe babel?), but think this may be an issue with Shift es6 module defaults rather than babel as it only happens with the Shift products. Please redirect me if not...

my code:

``` javascript
import parse from "shift-parser";
import analyzeScope, {ScopeType, DeclarationType} from "shift-scope";  
let ast = parse(`/*code*/`);
```

becomes:

``` javascript
var _shiftParser = require("shift-parser");
var _shiftParser2 = _interopRequireDefault(_shiftParser);
var _shiftScope = require("shift-scope");
var _shiftScope2 = _interopRequireDefault(_shiftScope);
var ast = (0, _shiftParser2["default"])("/*code*/");
```

where 'default' is no longer a function.

Can fix with standard require syntax:

``` javascript
let parse = require("shift-parser").parseScript;
let analyze = require('shift-scope').default; 
let ScopeType = require('shift-scope').ScopeType;
let DeclarationType = require('shift-scope').DeclarationType;
```

...but this doesn't match up with the instructions so a bit of digging required.

**Comment by michaelficarra** [comment]
Try using `--modules commonStrict` in your babel invocation.

**Comment by brokenalarms** [comment]
Hi Michael

Hmm, that does indeed fix the Shift modules to work with es6 imports; however, it seems to mean I then need to change every other place I am importing non-es6 modules to use require instead... (for example, every single import of React).

On balance, changing the 4 lines where I import Shift to use require is less of a hassle than changing all of my es5 imports...I was hoping there would be some middle ground, but it doesn't look like it then. Thanks very much for your help!

**Comment by michaelficarra** [comment]
Yes, we will reconsider using the default module compiler.

By the way, be careful when using shift-scope right now, as we have not yet upgraded it to support ES6 features or our new ES6 AST nodes. We'll be updating shift-scope, shift-fuzzer, and shift-validator (the remaining projects lacking ES6 support) very soon. The Java implementations have all already been updated.

**Comment by brokenalarms** [comment]
Ah, I guess that probably answers my issue #24 lodged in shift-scope too then...since the usage instructions had 'import' I assumed it was ES6-ready itself. Thanks a lot, that clears it up though maybe you could mention ES6 support is forthcoming in the .md to prevent other AST noobs like me from spending too much time wondering what they've done wrong :)

**Comment by michaelficarra** [comment]
The official Shift website should be out within the week, and this table should help people understand the current status of the projects:

<img width="729" alt="screen shot 2015-08-05 at 20 25 34" src="https://cloud.githubusercontent.com/assets/218840/9103197/3a366aa2-3bb0-11e5-9653-4b408afc2898.png">

**edit:** One of these links should work shortly:
- https://shapesecurity.github.io/shift-website
- http://shift-ast.org
