### ISSUE TITLE
Syntax object

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-parser-js#242]
`esprima` and many other `estools/*` experts this nice, handy, convenient, etc. object `Syntax` that has all AST node names in it. I can't find any such thing in `shift-*` tools :disappointed:
Do I look in the wrong place? Do you have any such handy tools for the AST arborist?

**Comment by michaelficarra** [comment]
Oh, what we have is far better. Check out https://github.com/shapesecurity/shift-spec-js.

**Comment by drom** [comment]
Yes, I suspected that would be you answer. One or Two lines of API usage guide would be helpful IMHO

**Comment by michaelficarra** [comment]
Of course. We will get to it, but it is not our highest priority yet. For now, it is easy enough to just require it and poke around.
