### ISSUE TITLE
Various RegExps are incorrectly accepted when `u` flag is set

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-parser-js#246]
(This is per comments in Test262 tests. I can't tell from reading the spec, myself.) List of incorrectly accepted RegExps with link to corresponding test follows. 
- [`/\1/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-dec-esc.js)
- [`/\c/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-char-esc.js)
- [`/[\w-a]/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-char-range-a.js)
- [`/[a-\w]/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-invalid-char-range-b.js)
- [`/\u{ff0000}/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-unicode-esc-bounds.js)
- [`/\u{1,}/u`](https://github.com/tc39/test262/blob/master/test/language/literals/regexp/u-unicode-esc-non-hex.js)

**Comment by michaelficarra** [comment]
Duplicate of #130.
