### ISSUE TITLE
ES6: modules: imports + exports + parseModule interface

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#25]
# [15.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-modules) Modules

### Syntax

<pre>
Module :
  ModuleBody<sub>opt</sub>

ModuleBody :
  ModuleItemList

ModuleItemList :
  ModuleItem
  ModuleItemList ModuleItem

ModuleItem :
  ImportDeclaration
  ExportDeclaration
  StatementListItem
</pre>

### Static Semantics: Early Errors

```
ModuleBody : ModuleItemList
```

- It is a Syntax Error if the LexicallyDeclaredNames of ModuleItemList contains any duplicate
entries.
- It is a Syntax Error if any element of the LexicallyDeclaredNames of ModuleItemList also occurs in
the VarDeclaredNames of ModuleItemList.
- It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries.
- It is a Syntax Error if any element of the ExportedBindings of ModuleItemList do not also occurs in
either the VarDeclaredNames of ModuleItemList, or the LexicallyDeclaredNames of
ModuleItemList.
- It is a Syntax Error if ModuleItemList Contains super.
- It is a Syntax Error if ModuleItemList Contains MetaProperty
- It is a Syntax Error if ContainsDuplicateLabels of ModuleItemList with argument « » is true.
- It is a Syntax Error if ContainsUndefinedBreakTarget of ModuleItemList with argument « » is true.© Ecma International 2014 321
- It is a Syntax Error if ContainsUndefinedContineTarget of ModuleItemList with arguments « » and « »
is true.

# [15.2.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-imports) Imports

extracted as #75.

# [15.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports) Exports

### Syntax

<pre>
ExportDeclaration :
  export * FromClause ;
  export ExportClause FromClause ;
  export ExportClause ;
  export VariableStatement
  export Declaration
  export default HoistableDeclaration[Default]
  export default ClassDeclaration[Default]
  export default [lookahead ∉ {function, class}] AssignmentExpression[In] ;

ExportClause :
  { }
  { ExportsList }
  { ExportsList , }

ExportsList :
  ExportSpecifier
  ExportsList , ExportSpecifier

ExportSpecifier :
  IdentifierName
  IdentifierName as IdentifierName
</pre>

### Static Semantics: Early Errors

```
ExportDeclaration : export ExportClause ;
```

- For each IdentifierName n in ReferencedBindings of ExportClause : It is a Syntax Error if StringValue of n is a ReservedWord or if the StringValue of n is one of: "implements", "interface", "let", "package", "private", "protected", "public", "static", or "yield".

**NOTE** The above rule means that each ReferencedBindings of ExportClause is treated as an IdentifierReference.

**Comment by ikarienator** [comment]
Close as separate issues are created.
