### ISSUE TITLE
Does this support whitespacing?

### ISSUE THREAD

**Issue by 7fe** [shapesecurity/shift-parser-js#253]
Does this support whitespacing?

**Comment by michaelficarra** [comment]
I don't know what this is supposed to mean.

**Comment by 7fe** [comment]
@michaelficarra Tokenization of white space so linebreaks are preserved when converting between the tokens and the original code.

**Comment by michaelficarra** [comment]
No, whitespace is not explicitly preserved. Additionally, the tokeniser is an implementation detail, and not part of the public API.
