### ISSUE TITLE
is that per spec  that ternary can not get mixed with rest?

### ISSUE THREAD

**Issue by mohsen1** [shapesecurity/shift-parser-js#254]
```
let a = false
let b = [1,2,3]
let c = [4,5,6]
let d = [7,8,9, a ? ...b : ...c];
```

Neither Babel or Shift like this. Is that per spec  that ternary can not get mixed with rest?

**Comment by LewisJEllis** [comment]
According to the [array initializer grammar](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-array-initializer), you can't do that, but you can do this:

``` javascript
let a = false;
let b = [1,2,3];
let c = [4,5,6];
let d = [7,8,9, ...a ? b : c];
```

and that parses with Shift and runs with Babel as expected.

**Comment by michaelficarra** [comment]
This is called a spread, not a rest. Rest is the LHS/binding form of spread.

**Comment by mohsen1** [comment]
Thanks! is `...a ? b : c` same as `...(a ? b : c)`?

**Comment by LewisJEllis** [comment]
Yes, the parentheses aren't necessary but might add clarity.

**Comment by michaelficarra** [comment]
Actually, it appears the parser is a bit too permissive here. The parentheses should be necessary, as an AssignmentExpression follows the `...` of a SpreadElement, not a ConditionalExpression. I'll open an issue.
