### ISSUE TITLE
Parser fails with "Not Reached" error when parsing `true && (a+="");`

### ISSUE THREAD

**Issue by jsoverson** [shapesecurity/shift-parser-js#255]
Parsing the string below hits [this line](https://github.com/shapesecurity/shift-parser-js/blob/es6/src/parser.js#L1130) in the parser:

`true && (a+="");`

All the other parsers on the [ast explorer](http://felix-kling.de/esprima_ast_explorer/) parse without errors.

**Comment by michaelficarra** [comment]
:open_mouth: wow! I will look into it soon.

**Comment by michaelficarra** [comment]
This appears to be a duplicate of https://github.com/shapesecurity/shift-parser-js/issues/189. @ikarienator do you know if it's possible to fix these without taking the strategy we do in shift-java of having every expression parsing method return a pair? The [`group.isLeft()` information here](https://github.com/shapesecurity/shift-java/blob/7316536383964567328a24e3498d1f5e4b92945a/src/main/java/com/shapesecurity/shift/parser/Parser.java#L1729-L1735) is lost.

**Comment by bakkot** [comment]
Closed via #274.
