### ISSUE TITLE
Error: Cannot find module 'shift-reducer'

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-parser-js#256]
My package: https://github.com/drom/jsof depends on:
`{"shift-parser": "^3.0.5"}`

It was passing before, but now it fails:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'shift-reducer'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    ...
```

I have noticed that internally `shift-parser` depends on: `{"shift-reducer": "^2.0.3"}`
But because of newer `{"shift-reducer": "^2.0.5"}` is out, it picks `v2.0.5`
And `v2.0.5` not packaged on npm with `dist` folder that brakes `shift-parser`

In essence `v2.0.3` --> `v2.0.5` was versioned as a patch but effectively breaks API compatibility?

**Comment by michaelficarra** [comment]
Sorry about that. I've unpublished `shift-reducer` version 2.0.5, which I accidentally published with an error. Re-installing your node modules should fix the issue.

**Comment by drom** [comment]
Thank you very much
