### ISSUE TITLE
Doesn't support ES6 module "import" statements.

### ISSUE THREAD

**Issue by rally25rs** [shapesecurity/shift-parser-js#258]
Does not support "import" statements.

```
var parseScript = require("shift-parser").parseScript;
var scriptAST = parseScript("import * as app from 'app';");
```

results in:

```
          throw this.createUnexpected(this.lookahead);
          ^
Error: [1:1]: Unexpected token "import"
```

**Comment by bakkot** [comment]
That's because `import` statements are not legal in Scripts. You want `parseModule`.

**Comment by rally25rs** [comment]
Ah! Thanks for the quick answer @bakkot 
I didn't even notice there were 2 parsers. That's what I get for quickly copy/pasting the "in node.js:" example from the README. :smile:
