### ISSUE TITLE
ES6: template strings

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#27]
# [11.8.6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components) Template Literal Lexical Components

### Syntax

<pre>
<i>Template</i> ::
  <i>NoSubstitutionTemplate</i>
  <i>TemplateHead</i>

<i>NoSubstitutionTemplate</i> ::
  <b>`</b> <i>TemplateCharacters</i><sub>opt</sub> <b>`</b>

<i>TemplateHead</i> ::
  <b>`</b> TemplateCharacters<sub>opt</sub> <b>${</b>

<i>TemplateSubstitutionTail</i> ::
  <i>TemplateMiddle</i>
  <i>TemplateTail</i>

<i>TemplateMiddle</i> ::
  <b>}</b> <i>TemplateCharacters</i><sub>opt</sub> <b>${</b>

<i>TemplateTail</i> ::
  <b>}</b> <i>TemplateCharacters</i><sub>opt</sub> <b>`</b>

<i>TemplateCharacters</i> ::
  <i>TemplateCharacter</i> <i>TemplateCharacters</i><sub>opt</sub>

<i>TemplateCharacter</i> ::
  <b>$</b> [lookahead ≠ <b>{</b> ]
  <b>\</b> <i>EscapeSequence</i>
  <i>LineContinuation</i>
  <i>LineTerminatorSequence</i>
  <i>SourceCharacter</i> but not one of <b>`</b> or <b>\</b> or <b>$</b> or <i>LineTerminator</i>

<i>LineContinuation</i> ::
  <b>\</b> <i>LineTerminatorSequence</i>

</pre>

# [12.2.8](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literals) Template Literals

### Syntax

<pre>
<i>TemplateLiteral</i><sub>[Yield]</sub> :
  <i>NoSubstitutionTemplate</i>
  <i>TemplateHead</i> <i>Expression</i><sub>[In, ?Yield]</sub> [Lexical goal InputElementTemplateTail] <i>TemplateSpans</i><sub>[?Yield]</sub>

<i>TemplateSpans</i><sub>[Yield]</sub> :
  <i>TemplateTail</i>
  <i>TemplateMiddleList</i><sub>[?Yield]</sub> [Lexical goal InputElementTemplateTail] <i>TemplateTail</i>

<i>TemplateMiddleList</i><sub>[Yield]</sub> :
  <i>TemplateMiddle</i> <i>Expression</i><sub>[In, ?Yield]</sub>
  <i>TemplateMiddleList</i><sub>[?Yield]</sub> [Lexical goal InputElementTemplateTail] <i>TemplateMiddle</i> <i>Expression</i><sub>[In, ?Yield]</sub>

<i>PrimaryExpression<i><sub>[Yield]</sub> :
  <i> TemplateLiteral</i><sub>[?Yield]</sub>
</pre>

# [11.8.6.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-static-semantics-tv-s-and-trv-s) Static Semantics: TV’s and TRV’s

**Comment by michaelficarra** [comment]
@ssrh: The `value` of a `TemplateLiteral` node should be the raw token value, no escape sequence interpreting.

**Comment by ssrh** [comment]
Having already written the code to translate the escape sequences, please verify that you are sure about this.

**Comment by michaelficarra** [comment]
I am sure. The escape sequences used must be preserved. If this tree was used for interpretation, that information would be required. It is accessible on the `raw` property of the first parameter of template tags.

**Comment by ikarienator** [comment]
Fixed by #97.
