### ISSUE TITLE
`yield` flag is passed to arrow bodies

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-parser-js#270]
`function*f(){x=>x*yield}` should parse (with `yield` being treated as an identifier expression); it does not.

**Comment by michaelficarra** [comment]
We should also add tests for yield in various arrow parameter positions if we don't already have them. See https://github.com/tc39/ecma262/issues/397 and https://github.com/Microsoft/ChakraCore/issues/333.

**Comment by bakkot** [comment]
@michaelficarra, [we do have such tests](https://github.com/shapesecurity/shift-parser-js/blob/6a342664b48c7cc2bebbeeeeb7935fd82fe83bd6/test/early-errors.js#L519-L525).
