### ISSUE TITLE
ES6: remove duplicate object property (besides __proto__) restriction

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#28]
### [B.3.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-__proto__-property-names-in-object-initializers) `__proto__` Property Names in Object Initializers

The following Early Error rule is added to those in 12.2.5.1:

    ObjectLiteral : { PropertyDefinitionList }

and

    ObjectLiteral : { PropertyDefinitionList , }

* It is a Syntax Error if PropertyNameList of PropertyDefinitionList contains any duplicate entries for `__proto__` and at least two of those entries were obtained from productions of the form `PropertyDefinition : PropertyName : AssignmentExpression`.

**Comment by dwightmulcahy** [comment]
I cried.
