### ISSUE TITLE
`[(a)] = 0` should parse

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-parser-js#284]
See [12.15.5.1](https://tc39.github.io/ecma262/#sec-destructuring-assignment-static-semantics-early-errors) and the preceding section. Note that `var [(a)] = 0` remains illegal.

**Comment by michaelficarra** [comment]
:cry:

**Comment by bakkot** [comment]
This and similar cases should be added to the 262 parser tests before closing this issue.
