### ISSUE TITLE
ES6: restrict assignment positions to bindings

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#30]
ES5 allowed arbitrary bindings in many positions (LHS of assignment, catch parameter, increment/decrement operand, LHS of for-in header, etc.). ES6 restricts these positions to valid bindings.

# [13.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns) Destructuring Binding Patterns

### Syntax

<pre>
BindingPattern[Yield,GeneratorParameter] :
  ObjectBindingPattern[?Yield,?GeneratorParameter]
  ArrayBindingPattern[?Yield,?GeneratorParameter]

ObjectBindingPattern[Yield,GeneratorParameter] :
  { }
  { BindingPropertyList[?Yield,?GeneratorParameter] }
  { BindingPropertyList[?Yield,?GeneratorParameter] , }

ArrayBindingPattern[Yield,GeneratorParameter] :
  [ Elision<sub>opt</sub> BindingRestElement[?Yield, ?GeneratorParameter]<sub>opt</sub> ]
  [ BindingElementList[?Yield, ?GeneratorParameter] ]
  [ BindingElementList[?Yield, ?GeneratorParameter] , Elision<sub>opt</sub> BindingRestElement[?Yield, ?GeneratorParameter]<sub>opt</sub> ]

BindingPropertyList[Yield,GeneratorParameter] :
  BindingProperty[?Yield, ?GeneratorParameter]
  BindingPropertyList[?Yield, ?GeneratorParameter] , BindingProperty[?Yield, ?GeneratorParameter]

BindingElementList[Yield,GeneratorParameter] :
  BindingElisionElement[?Yield, ?GeneratorParameter]
  BindingElementList[?Yield, ?GeneratorParameter] , BindingElisionElement[?Yield, ?GeneratorParameter]

BindingElisionElement[Yield,GeneratorParameter] :
  Elision<sub>opt</sub> BindingElement[?Yield, ?GeneratorParameter]

BindingProperty[Yield,GeneratorParameter] :
  SingleNameBinding[?Yield, ?GeneratorParameter]
  PropertyName[?Yield, ?GeneratorParameter] : BindingElement[?Yield, ?GeneratorParameter]

BindingElement[Yield,GeneratorParameter] :
  SingleNameBinding[?Yield, ?GeneratorParameter]
  [+GeneratorParameter] BindingPattern[?Yield,GeneratorParameter] Initializer[In]<sub>opt</sub>
  [~GeneratorParameter] BindingPattern[?Yield] Initializer[In, ?Yield]<sub>opt</sub>

SingleNameBinding [Yield, GeneratorParameter] :
  [+GeneratorParameter] BindingIdentifier[Yield] Initializer[In]<sub>opt</sub>
  [~GeneratorParameter] BindingIdentifier[?Yield] Initializer[In, ?Yield]<sub>opt</sub>

BindingRestElement[Yield, GeneratorParameter] :
  [+GeneratorParameter] ... BindingIdentifier[Yield]
  [~GeneratorParameter] ... BindingIdentifier[?Yield]
</pre>

# [12.14](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators) Assignment Operators

### Syntax

```
AssignmentExpression[In, Yield] :
  ConditionalExpression[?In, ?Yield]
  [+Yield] YieldExpression[?In]
  ArrowFunction[?In, ?Yield]
  LeftHandSideExpression[?Yield] = AssignmentExpression[?In, ?Yield]
  LeftHandSideExpression[?Yield] AssignmentOperator AssignmentExpression[?In, ?Yield]

AssignmentOperator : one of
  *=	/=	%=	+=	-=	<<=	>>=	>>>=	&=	^=	|=
```

### Static Semantics: Early Errors

```
AssignmentExpression : LeftHandSideExpression = AssignmentExpression
```

- It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and the lexical token sequence matched by LeftHandSideExpression cannot be parsed with no tokens left over using AssignmentPattern as the goal symbol.

- If LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and if the lexical token sequence matched by LeftHandSideExpression can be parsed with no tokens left over using AssignmentPattern as the goal symbol then the following rules are not applied. Instead, the Early Error rules for AssignmentPattern are used.

- It is an early Reference Error if LeftHandSideExpression is neither an ObjectLiteral nor an ArrayLiteral and IsValidSimpleAssignmentTarget of LeftHandSideExpression is false.

```
AssignmentExpression : LeftHandSideExpression AssignmentOperator AssignmentExpression
```

- It is an early Reference Error if IsValidSimpleAssignmentTarget of LeftHandSideExpression is false.

**Comment by benvinegar** [comment]
Should this be closed, then?
