### ISSUE TITLE
No parameter name after ... in a function signature does not produce an error in "fail" scipts

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#313]
[Script 69](https://github.com/tc39/test262-parser-tests/tree/master/fail/69.script.js): `function x(...[ a, b ]){}`
[Script 70](https://github.com/tc39/test262-parser-tests/tree/master/fail/70.script.js): `function x({ a: { w, x }, b: [y, z] }, ...[a, b, c]){}`
[Script 71](https://github.com/tc39/test262-parser-tests/tree/master/fail/71.script.js): `(function x(...[ a, b ]){})`
[Script 75](https://github.com/tc39/test262-parser-tests/tree/master/fail/75.script.js): `(function x({ a: { w, x }, b: [y, z] }, ...[a, b, c]){})`
[Script 76](https://github.com/tc39/test262-parser-tests/tree/master/fail/76.script.js): `(...[a, b]) => {}`
[Script 77](https://github.com/tc39/test262-parser-tests/tree/master/fail/77.script.js): `(a, ...[b]) => {}`
[Script 149](https://github.com/tc39/test262-parser-tests/tree/master/fail/149.script.js): `function x(...{ a }){}`
[Script 151](https://github.com/tc39/test262-parser-tests/tree/master/fail/151.script.js): `"use strict"; function x(a, ...[a]){}`
[Script 248](https://github.com/tc39/test262-parser-tests/tree/master/fail/248.script.js): `(a,...[a]) => 0;`
[Script 519](https://github.com/tc39/test262-parser-tests/tree/master/fail/519.script.js): `function x(...{ a }){}`

Expected: An Exception
Actual: No Exception

**Comment by bakkot** [comment]
These tests are all invalid. Opened https://github.com/tc39/test262-parser-tests/issues/9 and https://github.com/tc39/test262-parser-tests/issues/10.
