### ISSUE TITLE
Invalid pattern matching throws error with "earlyErrors" set as "false"

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#316]
earlyErrors: false

input [script 56](https://github.com/tc39/test262-parser-tests/tree/master/early/56.script.js) : `/[a-z]/s` 
input [script 641](https://github.com/tc39/test262-parser-tests/tree/master/early/641.script.js): `/./a`
input [script 642](https://github.com/tc39/test262-parser-tests/tree/master/early/642.script.js): `/./ii`

Expected: No Exceptions
Actual:  Exception
`.../shift-parser-js/dist/parser.js:1736
            throw this.createError("Invalid regular expression flag '" + f + "'");
            ^

**Comment by bakkot** [comment]
Our AST format can't represent regex literals with invalid flags. Closing as WONTFIX.
