### ISSUE TITLE
Using uninitialized let (destructing assignment) in the for statement  throws Error with "earlyErrors" set as false

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#318]
input [script 190](https://github.com/tc39/test262-parser-tests/tree/master/early/190.script.js): `for(let [let];;);`
input [script 205](https://github.com/tc39/test262-parser-tests/tree/master/early/205.script.js): `for(let [a, a];;)`
earlyErrors: false

Expected: No Exceptions
Actual: Exception

`
../shift-parser-js/dist/parser.js:748
              throw this.createError(_errors.ErrorMessages.UNINITIALIZED_BINDINGPATTERN_IN_FOR_INIT);
              ^

Error: [1:15]: Binding pattern appears without initializer in for statement init 
`

**Comment by bakkot** [comment]
This is a misclassified test; shift-parser is correct.

**Comment by michaelficarra** [comment]
@Shilpi3 It looks like script 205 is not what you've copied into this issue.

**Comment by bakkot** [comment]
Moved to https://github.com/tc39/test262-parser-tests/issues/11
