### ISSUE TITLE
 Setting property in shorthand illegally causes earlyErrors set as false Test to fail

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#319]
script 557 : `({ a = 0 });`
earlyErrors : false

Expected: No Exception
Actual: Exception
`
../shift-parser-js/dist/parser.js:1069
        throw this.firstExprError;
        ^

Error: [1:4]: Illegal property initializer`

**Comment by bakkot** [comment]
This is indeed [supposed](https://tc39.github.io/ecma262/#sec-object-initializer-static-semantics-early-errors) to be an early error, but our AST format can't represent that program. Closing as WONTFIX.
