### ISSUE TITLE
Too many dots causes earlyErrors "false" test to fail

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#320]
input [script 558](https://github.com/tc39/test262-parser-tests/tree/master/early): `(..a)`
input script 559: `(a, ...b)`
input script 560: `(((...a)))`
input script 561: `(((a, ...b))`

earlyErrors : false

`shift-parser-js/dist/parser.js:170
      throw this.createUnexpected(this.lookahead);
      ^

Error: [1:7]: Unexpected end of input`

**Comment by bakkot** [comment]
This are all misclassified: see the supplemental syntax section [here](https://tc39.github.io/ecma262/#sec-primary-expression). See https://github.com/tc39/test262-parser-tests/issues/11.
