### ISSUE TITLE
 Invalid left-hand side expression in postfix operation causes earlyErrors "false" test to fail

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#321]
input [script 563](https://github.com/tc39/test262-parser-tests/blob/master/early/558.script.js): `0++`
input [script 564](https://github.com/tc39/test262-parser-tests/blob/master/early/564.script.js): `0--`
input [script 565](https://github.com/tc39/test262-parser-tests/blob/master/early/565.script.js): `++0`
input [script 566](https://github.com/tc39/test262-parser-tests/blob/master/early/566.script.js): `--0`

earlyErrors: false
Expected: No Exception
Actual: Exception
`
../shift-parser-js/dist/parser.js:1533
        throw this.createErrorWithLocation(startLocation, _errors.ErrorMessages.INVALID_UPDATE_OPERAND);
        ^

Error: [1:1]: Increment/decrement target must be an identifier or member expression `

**Comment by bakkot** [comment]
This is indeed [supposed](https://tc39.github.io/ecma262/#sec-update-expressions-static-semantics-early-errors) to be an early error, but our AST format can't represent that program. Closing as WONTFIX.
