### ISSUE TITLE
Using Invalid destructuring assignment target causes earlyErrors "false" test to fail

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#322]
Input [string 567](https://github.com/tc39/test262-parser-tests/blob/master/early/558.script.js): `({a: 0} = 0);`
Input [string 568](https://github.com/tc39/test262-parser-tests/blob/master/early/568.script.js): `({get a(){}} = 0)`
Input [string 570](https://github.com/tc39/test262-parser-tests/blob/master/early/570.script.js): `({set a(b){}} = 0)`
Input [string 571](https://github.com/tc39/test262-parser-tests/blob/master/early/571.script.js): `[0] = 0`
Input [string 577](https://github.com/tc39/test262-parser-tests/blob/master/early/577.script.js): `[...{a: 0}] = 0;`
Input [string 578](https://github.com/tc39/test262-parser-tests/blob/master/early/578.script.js): `[...[0]] = 0;`
Input [string 579](https://github.com/tc39/test262-parser-tests/blob/master/early/579.script.js): `[...0] = 0;`
Input [string 580](https://github.com/tc39/test262-parser-tests/blob/master/early/580.script.js): `[...new a] = 0;`

earlyErrors as false
Expected: No Exception 
Actual: Exception

`..shift-parser-js/dist/parser.js:1182
          throw this.createError(_errors.ErrorMessages.INVALID_LHS_IN_ASSIGNMENT);
          ^

Error: [1:9]: Invalid left-hand side in assignment`

**Comment by bakkot** [comment]
These are all misclassified: see the supplemental syntax section [here](https://tc39.github.io/ecma262/#sec-destructuring-assignment). See tc39/test262-parser-tests#11.
