### ISSUE TITLE
Using Invalid left-hand side in assignment causes earlyErrors "false" test to fail

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#323]
Input [string 572](https://github.com/tc39/test262-parser-tests/blob/master/early/572.script.js) : `0=0;`
Input [string 574](https://github.com/tc39/test262-parser-tests/blob/master/early/574.script.js): `({a} += 0)`
Input [string 575:](https://github.com/tc39/test262-parser-tests/blob/master/early/575.script.js) `[a] *= 0;`
Input [string 581:](https://github.com/tc39/test262-parser-tests/blob/master/early/581.script.js) `for({a: 0} in 0);`
Input [string 582](https://github.com/tc39/test262-parser-tests/blob/master/early/582.script.js): `for([0] in 0);`
Input [string 583](https://github.com/tc39/test262-parser-tests/blob/master/early/583.script.js): `for({a: 0} of 0);`
Input [string 585](https://github.com/tc39/test262-parser-tests/blob/master/early/585.script.js):`for([0] of 0);`
Input [string 586](https://github.com/tc39/test262-parser-tests/blob/master/early/586.script.js): `for(0 in 0)`
Input [string 587](https://github.com/tc39/test262-parser-tests/blob/master/early/587.script.js): `for(0 of 0);`
Input [string 588](https://github.com/tc39/test262-parser-tests/blob/master/early/588.script.js): `for(({a: 0}) in 0);`
Input [string 589](https://github.com/tc39/test262-parser-tests/blob/master/early/589.script.js): `for(([0]) in 0);`
Input [string 590](https://github.com/tc39/test262-parser-tests/blob/master/early/590.script.js): `for(({a: 0}) of 0);`
Input [string 591](https://github.com/tc39/test262-parser-tests/blob/master/early/591.script.js): `for(([0]) of 0);`
Input [string 592](https://github.com/tc39/test262-parser-tests/blob/master/early/592.script.js): `for((0) in 0);`
Input [string 593](https://github.com/tc39/test262-parser-tests/blob/master/early/593.script.js): `for((0) of 0);`

earlyErrors as false
Expected: No Exception
Actual: Exception

`..shift-parser-js/dist/parser.js:1182
throw this.createError(_errors.ErrorMessages.INVALID_LHS_IN_ASSIGNMENT);
^

Error: [1:9]: Invalid left-hand side in assignment`

**Comment by bakkot** [comment]
These are indeed supposed ([here](https://tc39.github.io/ecma262/#sec-assignment-operators-static-semantics-early-errors) and [here](https://tc39.github.io/ecma262/#sec-for-in-and-for-of-statements-static-semantics-early-errors)) to be an early error, but our AST format can't represent these programs. Closing as WONTFIX.
