### ISSUE TITLE
ES5 compatibility

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-parser-js#344]
Looks like with the recent updates:
v5.0.3 https://github.com/shapesecurity/shift-parser-js/commit/912b07552f4f457418e478b1ef96cfff45f34a6d
`new Set()` was introduced and went through the Babel into `dist` code.
This change brakes ES5 compatibility.

**Comment by michaelficarra** [comment]
@drom Published `5.0.4`.

**Comment by drom** [comment]
@michaelficarra you can use Babel polyfill fo set.
```js
require('core-js/fn/set');
```

**Comment by michaelficarra** [comment]
@drom That's okay, we didn't really need to use `Set`. We will use it (without the polyfill) in the next major version.
