### ISSUE TITLE
incorrectly disallows `in` expressions in function-bodied arrows in for statement initialisers

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#348]
This should be allowed but is not:

```js
for (() => { this in a };;);
```

Originally reported by @lydell in https://github.com/shapesecurity/shift-codegen-js/issues/54

**Comment by lydell** [comment]
Slight correction:

This _is_ currently allowed:

```js
for (() => {(this in a)};;);
```

And this _should_ be allowed but currently isn’t:

```js
for (() => {this in a};;);
```

**Comment by michaelficarra** [comment]
Correct. Copy/paste error. I will edit my original message to avoid confusion.
