### ISSUE TITLE
Generate AST with comments

### ISSUE THREAD

**Issue by simondel** [shapesecurity/shift-parser-js#352]
When I parse the following code on the [online parser](http://shift-ast.org/parser.html) I don't get any comments in the output:
```
// Hello world!
/* good morning */
```

How can I add the comments to the AST?

**Comment by bakkot** [comment]
You can't. Comments aren't usually included in an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree); the parser discards them.

We'd like to think about how best to represent concrete syntax too, at some point, but I don't think we have a good model for that right now. It's pretty tricky to do well.

**Comment by michaelficarra** [comment]
Comments will never be attached to the AST because there's no good way to choose which node to associate a comment with. But I can imagine the parse-with-location function also producing a list of comments with their positions.

**Comment by bakkot** [comment]
Fixed by #365.
