### ISSUE TITLE
"Error: Not reached" when trying to parse `(([...a=1]))`

### ISSUE THREAD

**Issue by lydell** [shapesecurity/shift-parser-js#355]
```
> require("shift-parser").parseScript("(([...a=1]))")
Error: Not reached
```

**Comment by bakkot** [comment]
Whoops. I seem to have introduced this in 1e18775ad4fe005b31f6bd1ad423295e217d62b0.

**Comment by bakkot** [comment]
Actually, no, this isn't a regression from 1e18775; we incorrectly reject it either way, just with a different error.
