### ISSUE TITLE
Location information for FunctionBody should includes braces

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-parser-js#371]
and FormalParameters should include parentheses.

This is particularly relevant if we pursue #370, but also, it's just nicer, I think.

Pros:
- Better intuition
- Adds the property that every node other than an empty Script or Module spans at least one token, simplifying some internal logic
- More consistent with other parsers

Cons:
- Does not match the ES grammar
- Arguably a breaking change
- Arguably inconsistent with grouped expressions, which do not include parentheses (and IMO should not)
- Would require making the corresponding change to shift-java's CodegenWithLocation

**Comment by michaelficarra** [comment]
Fixed by #373.
