### ISSUE TITLE
Preserve backslash in regexp

### ISSUE THREAD

**Issue by mhaagens** [shapesecurity/shift-parser-js#375]
Any way I can preserve the backslash in the regexp of "test", as seen here?
It just returns ```test: /.js$/``` when I run it through parseModule.

<img width="546" alt="screen shot 2017-10-21 at 22 48 38" src="https://user-images.githubusercontent.com/3270517/31855770-107dd6ee-b6b2-11e7-8773-add52dc6623b.png">

**Comment by bakkot** [comment]
That's a normal JavaScript string escaping thing, nothing to do with Shift. By the time Shift sees it, there's no backslash there:

```js
`\.` === '.' // true
```

Just put another backslash in front of it, or tag your template with `String.raw`.

**Comment by mhaagens** [comment]
Thank you so much for helping me out, and sorry for opening an unrelated issue!
