### ISSUE TITLE
Script throwing error for the wrong reason

### ISSUE THREAD

**Issue by Shilpi3** [shapesecurity/shift-parser-js#417]
The script  `(async (...x = []) => {});` should throw syntax error as REST Formal parameters do not accept default values. However, the script is throwing an error for the wrong reason. Following is the output through the parser.
```
throw new Error('Not reached');
```

The test is a part of the [test262](https://github.com/tc39/test262/blob/master/test/language/expressions/async-arrow-function/dflt-params-rest.js) test suite.

**Comment by bakkot** [comment]
Fixed by #418.
