### ISSUE TITLE
default parameters for a strict mode function should be in strict mode

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#44]
This should fail:

```js
function f(a = function(eval){}) {
  "use strict";
}
```

**Comment by ikarienator** [comment]
This kind of things make me want to check theses errors in a second pass.

**Comment by zenparsing** [comment]
Use strict directives are truly obnoxious now that we have default parameters.

The strategy that I employ in esparse is to put "potential" strict mode errors on the context stack.  When the strictness of a context is resolved as "strict", and there are pending strict mode errors, it throws.

**Comment by michaelficarra** [comment]
@zenparsing: See #56. We plan to change to a two-pass architecture, deferring all early errors to the optional second pass. This way, a user can opt for a fast parse that only guarantees the input is matched by the ES grammar, and it will greatly simplify the intermediate representations in the parser.

**Comment by ikarienator** [comment]
Probably move to Two-Phase Parsing milestone?

**Comment by michaelficarra** [comment]
Agreed.

**Comment by michaelficarra** [comment]
We should add a test in `test/early-errors.js` under 14.1.2 and 14.4.1 for the early errors with text

> If the source code matching this production is strict code, the Early Error rules for StrictFormalParameters : FormalParameters are applied.
