### ISSUE TITLE
Add String.raw values to LiteralStringExpression types using template tags

### ISSUE THREAD

**Issue by ghost** [shapesecurity/shift-parser-js#441]
If I run the following code:
```
let Shift = require('shift-ast/checked');

let src = `
0 + 1;
`;

let replaced = applyTemplate(src, {
  foo: node => new Shift.LiteralNumericExpression({ value: node.value + 1 }),
});
```

I receive the following error:

```
TypeError: Provided replacements for nodes named "foo", but no corresponding nodes were found.
```

 Is there any way to apply template based on the node type of AST rather than the name? My use case is to get all LiteralNumericExpressions and make its value be `node.value+1`.

**Comment by michaelficarra** [comment]
You're looking for [shift-reducer](https://github.com/shapesecurity/shift-reducer-js). We actually have your exact use case as [one of the examples](https://github.com/shapesecurity/shift-reducer-js/blob/es2018/examples/increment.js). Closing as this isn't the appropriate repo.
