### ISSUE TITLE
Anyway to parse a SHIFT AST back to JavaScript codes?

### ISSUE THREAD

**Issue by zhaohan-xi** [shapesecurity/shift-parser-js#443]
Hi Dear Author, seems like this powerful tool can transfer the JS codes into SHIFT AST, but is there any way to transfer it back? And if yes, can this process be done by python?

**Comment by bakkot** [comment]
> is there any way to transfer it back

[Yes](https://github.com/shapesecurity/shift-codegen-js).

> And if yes, can this process be done by python?

No, the Shift tooling currently only runs in Java and JavaScript.
