### ISSUE TITLE
Destructuring rest not supported in object assignments

### ISSUE THREAD

**Issue by ceres-c** [shapesecurity/shift-parser-js#457]
Statements such as
```{a, b, ...rest} = {a: 1, b: 2 c: 30, d: 40}```
are not supported and shift-parser throws an `Unexpected token "..."` Error.

If I get this right, it should be considered [part of the language](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-destructuring-assignment) now, but correct me if I'm wrong and this was left out as a deliberate choice

**Comment by bakkot** [comment]
`{a, b, ...rest} = {a: 1, b: 2, c: 30, d: 40}` is not legal JavaScript (even with the missing comma added). You need to wrap it in parentheses for it to be parsed as an assignment expression, as in `({a, b, ...rest} = {a: 1, b: 2, c: 30, d: 40})`. And then it will indeed be parsed (at least with the latest version of shift-parser).

**Comment by ceres-c** [comment]
Now I feel terribly stupid, sorry. I was experimenting with assignments to both arrays and objects and I forgot the fundamental parentheses while quickly modifying my test code. :(
Node console accepting the expression without the parentheses didn't help me either

Sorry again and thanks for the great libs you people built

**Comment by bakkot** [comment]
No worries. The repl thing does tend to trip people up.
