### ISSUE TITLE
constant declarations without initialisers are wrongly rejected

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#5]
This is valid from what I can tell, but rejected by the parser.

```js
const a;
```

**Comment by michaelficarra** [comment]
Never mind, I found the restriction in [13.2.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations-static-semantics-early-errors):

> It is a Syntax Error if Initializer is not present and IsConstantDeclaration of the LexicalDeclaration containing this production is true.

**Comment by ikarienator** [comment]
Ha... I wrongly fixed it.

**Comment by michaelficarra** [comment]
In shift-java, right? I don't see a commit from you in this repo.

**Comment by ikarienator** [comment]
Yes, in shift-java.
