### ISSUE TITLE
[ES5] DoWhileStatements do not end with optional semicolon

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#58]

**Comment by michaelficarra** [comment]
This is not enough information. Expand on what you mean. Is this a bug or enhancement or question? Add a label.

**Comment by ikarienator** [comment]
For example `do ; while(0) 0` should not parse. It does now.

**Comment by emattson** [comment]
@ikarienator if ```do ; while(0) ``` is the whole program this should parse properly correct?

**Comment by michaelficarra** [comment]
Not in ES5. Only in ES6.

**Comment by ikarienator** [comment]
FYI, that will parse in ES5 because of automatic semicolon insertion.
