### ISSUE TITLE
Streaming parser

### ISSUE THREAD

**Issue by rektide** [shapesecurity/shift-parser-js#6]
This parsers appears entirely synchronous- one has to wait for a complete parse tree to finish being parsed. I'd love to see a (generators-based) implementation that can emit expressions & other structures as they are parsed.

**Comment by ikarienator** [comment]
That sounds awesome though...

**Comment by michaelficarra** [comment]
Related: https://github.com/djspiewak/sparse

**Comment by ikarienator** [comment]
That lack of lazy evaluation makes it a bit harder. A lazy evaluated AST cannot be expressed using arrays but lazy lists.

It is more promising to be done in the Java one but I just recently removed the support of lazy lists...

**Comment by michaelficarra** [comment]
The lazy lists, like all lazy structures in JS, would need to be represented using generators.

**Comment by michaelficarra** [comment]
Closing this until someone demonstrates a need for this feature and more details about a desired interface.

**Comment by rektide** [comment]
There's a ton of use cases in the gulp-toolchain workflow where it'd be great to be pumping streams at a JS parser on the fly, versus waiting for every single file to fully resolve, be stored in memory, and then shipped at once into parse. Anyone whose used gulp ought to be able to give you four or five pet projects they'd really like to see that would be possible if this tech were available.

In plenty of circumstances it'd be a valid workaround to try to wait until you have complete, parseable fragments, and instantiate a parser for each fragment, but the really smart really fun to work with tech like browserify is 100% to the core streaming. Waiting for things to complete and doing the work incrementally doesn't fit snuggly in this paradigm.

**Comment by ikarienator** [comment]
What about the interface? Do you want to change all the lIst in the AST to generators?

**Comment by michaelficarra** [comment]
@rektide: It really depends on your use case. Yes, I will admit that if you wanted to do something simple like collect all the identifier names used throughout a program in no particular order, a streaming event-emitting parser would be nice. But if you want to do anything related to traversing/reducing, you are going to need the entire AST structure to be built up before doing anything. I assert that the *vast majority* of real word use cases fall into that second bucket. In fact, I couldn't even come up with a use case for a streaming parser that couldn't be solved with a simple streaming lexer.

**Comment by rektide** [comment]
Esprima's issue #92 is for a capability like this. Ariya just closed it, pending someone coming up with a sensible interface or implementation strategy. My apologies for not convincing anyone this is an interesting capability or power to have. Perhaps greater men will some day better illuminate the potentials. https://code.google.com/p/esprima/issues/detail?id=92
