### ISSUE TITLE
ES6 Support: Classes

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-parser-js#82]
# [14.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions) Class Definitions

## Syntax

<pre>
<i>ClassDeclaration</i>[Yield, Default] :
    <b>class</b> <i>BindingIdentifier</i><sub>[?Yield]</sub> <i>ClassTail</i><sub>[?Yield]</sub>
    [+Default] <b>class</b> <i>ClassTail</i><sub>[?Yield]</sub>

<i>ClassExpression</i>[Yield,GeneratorParameter] :
    <b>class</b> <i>BindingIdentifier</i><sub>[?Yield]</sub><sub>opt</sub> <i>ClassTail</i><sub>[?Yield,?GeneratorParameter]</sub>

<i>ClassTail</i>[Yield,GeneratorParameter] :
    [~GeneratorParameter] <i>ClassHeritage</i><sub>[?Yield]</sub><sub>opt</sub> <b>{</b> <i>ClassBody</i><sub>[?Yield]</sub><sub>opt</sub> <b>}</b>
    [+GeneratorParameter] <i>ClassHeritage<i><sub>opt</sub> <b>{</b> <i>ClassBody</i><sub>opt</sub></sub> <b>}</b>

<i>ClassHeritage</i>[Yield] :
    <b>extends</b> <i>LeftHandSideExpression</i><sub>[?Yield]</sub>

<i>ClassBody</i>[Yield] :
    <i>ClassElementList</i><sub>[?Yield]</sub>

<i>ClassElementList</i>[Yield] :
    <i>ClassElement</i><sub>[?Yield]</sub>
    <i>ClassElementList</i><sub>[?Yield]</sub> <i>ClassElement</i><sub>[?Yield]</sub>

<i>ClassElement</i>[Yield] :
    <i>MethodDefinition</i>[?Yield]
    <b>static</b> <i>MethodDefinition</i>[?Yield]
    <b>;</b>
</pre>

#### References:
<pre>
<i>Declaration</i>[Yield]:
    <i>ClassDeclaration</i><sub>[?Yield]</sub>

<i>ExportDeclaration</i> :
    <b>export</b> <b>default</b> <i>ClassDeclaration</i><sub>[Default]</sub>

<i>PrimaryExpression</i> :
    <i>ClassExpression</i>

</pre>

## Early Errors

```
ClassBody : ClassElementList
```

It is a Syntax Error if `PrototypePropertyNameList` of `ClassElementList` contains more than one occurrence of `"constructor"`.

```
ClassElement : MethodDefinition
```

It is a Syntax Error if `PropName` of `MethodDefinition` is not "constructor" and `HasDirectSuper(MethodDefinition)` is `true`.

It is a Syntax Error if `PropName` of `MethodDefinition` is "constructor" and `SpecialMethod` of `MethodDefinition` is `true`.

```
ClassElement : static MethodDefinition
```
It is a Syntax Error if `HasDirectSuper(MethodDefinition)` is true.
It is a Syntax Error if `PropName` of `MethodDefinition` is `"prototype"`.

**Comment by michaelficarra** [comment]
Fixed by #85.
